/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CostingItem = IDL.Record({
  'rmId' : IDL.Nat,
  'quantity' : IDL.Float64,
});
export const CostingRecord = IDL.Record({
  'id' : IDL.Nat,
  'gsmRangeId' : IDL.Nat,
  'layerId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalCost' : IDL.Float64,
  'gradeId' : IDL.Nat,
  'length' : IDL.Float64,
  'quantity' : IDL.Nat,
  'items' : IDL.Vec(CostingItem),
  'width' : IDL.Float64,
});
export const Grade = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const GsmRange = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'minGsm' : IDL.Float64,
  'maxGsm' : IDL.Float64,
});
export const Layer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const RM = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'unitCost' : IDL.Float64,
});
export const CalculatedItem = IDL.Record({
  'baseQty' : IDL.Float64,
  'rmId' : IDL.Nat,
  'calculatedQty' : IDL.Float64,
});
export const ProductionEntry = IDL.Record({
  'id' : IDL.Nat,
  'costingRecordId' : IDL.Nat,
  'productionQtyMT' : IDL.Float64,
  'createdAt' : IDL.Int,
  'calculatedItems' : IDL.Vec(CalculatedItem),
});

export const idlService = IDL.Service({
  'createCostingRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Vec(CostingItem),
      ],
      [IDL.Int],
      [],
    ),
  'createGrade' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createGsmRange' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createLayer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createProductionEntry' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Int], []),
  'createRM' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [IDL.Nat], []),
  'deleteCostingRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGrade' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGsmRange' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLayer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProductionEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteRM' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCostingRecord' : IDL.Func([IDL.Nat], [IDL.Opt(CostingRecord)], ['query']),
  'getGrade' : IDL.Func([IDL.Nat], [IDL.Opt(Grade)], ['query']),
  'getGsmRange' : IDL.Func([IDL.Nat], [IDL.Opt(GsmRange)], ['query']),
  'getLayer' : IDL.Func([IDL.Nat], [IDL.Opt(Layer)], ['query']),
  'getRM' : IDL.Func([IDL.Nat], [IDL.Opt(RM)], ['query']),
  'listCostingRecords' : IDL.Func([], [IDL.Vec(CostingRecord)], ['query']),
  'listGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
  'listGsmRanges' : IDL.Func([], [IDL.Vec(GsmRange)], ['query']),
  'listLayers' : IDL.Func([], [IDL.Vec(Layer)], ['query']),
  'listProductionEntries' : IDL.Func([], [IDL.Vec(ProductionEntry)], ['query']),
  'listRMs' : IDL.Func([], [IDL.Vec(RM)], ['query']),
  'updateGrade' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateGsmRange' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateLayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateRM' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CostingItem = IDL.Record({
    'rmId' : IDL.Nat,
    'quantity' : IDL.Float64,
  });
  const CostingRecord = IDL.Record({
    'id' : IDL.Nat,
    'gsmRangeId' : IDL.Nat,
    'layerId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalCost' : IDL.Float64,
    'gradeId' : IDL.Nat,
    'length' : IDL.Float64,
    'quantity' : IDL.Nat,
    'items' : IDL.Vec(CostingItem),
    'width' : IDL.Float64,
  });
  const Grade = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const GsmRange = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'minGsm' : IDL.Float64,
    'maxGsm' : IDL.Float64,
  });
  const Layer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const RM = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'unitCost' : IDL.Float64,
  });
  const CalculatedItem = IDL.Record({
    'baseQty' : IDL.Float64,
    'rmId' : IDL.Nat,
    'calculatedQty' : IDL.Float64,
  });
  const ProductionEntry = IDL.Record({
    'id' : IDL.Nat,
    'costingRecordId' : IDL.Nat,
    'productionQtyMT' : IDL.Float64,
    'createdAt' : IDL.Int,
    'calculatedItems' : IDL.Vec(CalculatedItem),
  });
  
  return IDL.Service({
    'createCostingRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Vec(CostingItem),
        ],
        [IDL.Int],
        [],
      ),
    'createGrade' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createGsmRange' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createLayer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createProductionEntry' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Int], []),
    'createRM' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [IDL.Nat], []),
    'deleteCostingRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGrade' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGsmRange' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLayer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProductionEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteRM' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCostingRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CostingRecord)],
        ['query'],
      ),
    'getGrade' : IDL.Func([IDL.Nat], [IDL.Opt(Grade)], ['query']),
    'getGsmRange' : IDL.Func([IDL.Nat], [IDL.Opt(GsmRange)], ['query']),
    'getLayer' : IDL.Func([IDL.Nat], [IDL.Opt(Layer)], ['query']),
    'getRM' : IDL.Func([IDL.Nat], [IDL.Opt(RM)], ['query']),
    'listCostingRecords' : IDL.Func([], [IDL.Vec(CostingRecord)], ['query']),
    'listGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
    'listGsmRanges' : IDL.Func([], [IDL.Vec(GsmRange)], ['query']),
    'listLayers' : IDL.Func([], [IDL.Vec(Layer)], ['query']),
    'listProductionEntries' : IDL.Func(
        [],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'listRMs' : IDL.Func([], [IDL.Vec(RM)], ['query']),
    'updateGrade' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateGsmRange' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateLayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateRM' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };