/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalculatedItem {
  'baseQty' : number,
  'rmId' : bigint,
  'calculatedQty' : number,
}
export interface CostingItem { 'rmId' : bigint, 'quantity' : number }
export interface CostingRecord {
  'id' : bigint,
  'gsmRangeId' : bigint,
  'layerId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'totalCost' : number,
  'gradeId' : bigint,
  'length' : number,
  'quantity' : bigint,
  'items' : Array<CostingItem>,
  'width' : number,
}
export interface Grade {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface GsmRange {
  'id' : bigint,
  'name' : string,
  'minGsm' : number,
  'maxGsm' : number,
}
export interface Layer {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface ProductionEntry {
  'id' : bigint,
  'costingRecordId' : bigint,
  'productionQtyMT' : number,
  'createdAt' : bigint,
  'calculatedItems' : Array<CalculatedItem>,
}
export interface RM {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'unitCost' : number,
}
export interface _SERVICE {
  'createCostingRecord' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      bigint,
      number,
      number,
      bigint,
      Array<CostingItem>,
    ],
    bigint
  >,
  'createGrade' : ActorMethod<[string, string], bigint>,
  'createGsmRange' : ActorMethod<[string, number, number], bigint>,
  'createLayer' : ActorMethod<[string, string], bigint>,
  'createProductionEntry' : ActorMethod<[bigint, number], bigint>,
  'createRM' : ActorMethod<[string, number, string], bigint>,
  'deleteCostingRecord' : ActorMethod<[bigint], boolean>,
  'deleteGrade' : ActorMethod<[bigint], boolean>,
  'deleteGsmRange' : ActorMethod<[bigint], boolean>,
  'deleteLayer' : ActorMethod<[bigint], boolean>,
  'deleteProductionEntry' : ActorMethod<[bigint], boolean>,
  'deleteRM' : ActorMethod<[bigint], boolean>,
  'getCostingRecord' : ActorMethod<[bigint], [] | [CostingRecord]>,
  'getGrade' : ActorMethod<[bigint], [] | [Grade]>,
  'getGsmRange' : ActorMethod<[bigint], [] | [GsmRange]>,
  'getLayer' : ActorMethod<[bigint], [] | [Layer]>,
  'getRM' : ActorMethod<[bigint], [] | [RM]>,
  'listCostingRecords' : ActorMethod<[], Array<CostingRecord>>,
  'listGrades' : ActorMethod<[], Array<Grade>>,
  'listGsmRanges' : ActorMethod<[], Array<GsmRange>>,
  'listLayers' : ActorMethod<[], Array<Layer>>,
  'listProductionEntries' : ActorMethod<[], Array<ProductionEntry>>,
  'listRMs' : ActorMethod<[], Array<RM>>,
  'updateGrade' : ActorMethod<[bigint, string, string], boolean>,
  'updateGsmRange' : ActorMethod<[bigint, string, number, number], boolean>,
  'updateLayer' : ActorMethod<[bigint, string, string], boolean>,
  'updateRM' : ActorMethod<[bigint, string, number, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];