/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Grade {
    id: bigint;
    name: string;
    description: string;
}
export interface ProductionEntry {
    id: bigint;
    costingRecordId: bigint;
    productionQtyMT: number;
    createdAt: bigint;
    calculatedItems: Array<CalculatedItem>;
}
export interface CalculatedItem {
    baseQty: number;
    rmId: bigint;
    calculatedQty: number;
}
export interface GsmRange {
    id: bigint;
    name: string;
    minGsm: number;
    maxGsm: number;
}
export interface RM {
    id: bigint;
    name: string;
    unit: string;
    unitCost: number;
}
export interface CostingRecord {
    id: bigint;
    gsmRangeId: bigint;
    layerId: bigint;
    name: string;
    createdAt: bigint;
    totalCost: number;
    gradeId: bigint;
    length: number;
    quantity: bigint;
    items: Array<CostingItem>;
    width: number;
}
export interface CostingItem {
    rmId: bigint;
    quantity: number;
}
export interface Layer {
    id: bigint;
    name: string;
    description: string;
}
export interface backendInterface {
    createCostingRecord(name: string, gradeId: bigint, layerId: bigint, gsmRangeId: bigint, width: number, length: number, quantity: bigint, items: Array<CostingItem>): Promise<bigint>;
    createGrade(name: string, description: string): Promise<bigint>;
    createGsmRange(name: string, minGsm: number, maxGsm: number): Promise<bigint>;
    createLayer(name: string, description: string): Promise<bigint>;
    createProductionEntry(costingRecordId: bigint, productionQtyMT: number): Promise<bigint>;
    createRM(name: string, unitCost: number, unit: string): Promise<bigint>;
    deleteCostingRecord(id: bigint): Promise<boolean>;
    deleteGrade(id: bigint): Promise<boolean>;
    deleteGsmRange(id: bigint): Promise<boolean>;
    deleteLayer(id: bigint): Promise<boolean>;
    deleteProductionEntry(id: bigint): Promise<boolean>;
    deleteRM(id: bigint): Promise<boolean>;
    getCostingRecord(id: bigint): Promise<CostingRecord | null>;
    getGrade(id: bigint): Promise<Grade | null>;
    getGsmRange(id: bigint): Promise<GsmRange | null>;
    getLayer(id: bigint): Promise<Layer | null>;
    getRM(id: bigint): Promise<RM | null>;
    listCostingRecords(): Promise<Array<CostingRecord>>;
    listGrades(): Promise<Array<Grade>>;
    listGsmRanges(): Promise<Array<GsmRange>>;
    listLayers(): Promise<Array<Layer>>;
    listProductionEntries(): Promise<Array<ProductionEntry>>;
    listRMs(): Promise<Array<RM>>;
    updateGrade(id: bigint, name: string, description: string): Promise<boolean>;
    updateGsmRange(id: bigint, name: string, minGsm: number, maxGsm: number): Promise<boolean>;
    updateLayer(id: bigint, name: string, description: string): Promise<boolean>;
    updateRM(id: bigint, name: string, unitCost: number, unit: string): Promise<boolean>;
}
import type { CostingRecord as _CostingRecord, Grade as _Grade, GsmRange as _GsmRange, Layer as _Layer, RM as _RM } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCostingRecord(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: bigint, arg7: Array<CostingItem>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCostingRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCostingRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createGrade(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGrade(arg0, arg1);
            return result;
        }
    }
    async createGsmRange(arg0: string, arg1: number, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGsmRange(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGsmRange(arg0, arg1, arg2);
            return result;
        }
    }
    async createLayer(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLayer(arg0, arg1);
            return result;
        }
    }
    async createProductionEntry(arg0: bigint, arg1: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductionEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductionEntry(arg0, arg1);
            return result;
        }
    }
    async createRM(arg0: string, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRM(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRM(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCostingRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCostingRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCostingRecord(arg0);
            return result;
        }
    }
    async deleteGrade(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGrade(arg0);
            return result;
        }
    }
    async deleteGsmRange(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGsmRange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGsmRange(arg0);
            return result;
        }
    }
    async deleteLayer(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLayer(arg0);
            return result;
        }
    }
    async deleteProductionEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductionEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductionEntry(arg0);
            return result;
        }
    }
    async deleteRM(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRM(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRM(arg0);
            return result;
        }
    }
    async getCostingRecord(arg0: bigint): Promise<CostingRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostingRecord(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostingRecord(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrade(arg0: bigint): Promise<Grade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrade(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrade(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGsmRange(arg0: bigint): Promise<GsmRange | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGsmRange(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGsmRange(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLayer(arg0: bigint): Promise<Layer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLayer(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLayer(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRM(arg0: bigint): Promise<RM | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRM(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRM(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCostingRecords(): Promise<Array<CostingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCostingRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCostingRecords();
            return result;
        }
    }
    async listGrades(): Promise<Array<Grade>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGrades();
            return result;
        }
    }
    async listGsmRanges(): Promise<Array<GsmRange>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGsmRanges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGsmRanges();
            return result;
        }
    }
    async listLayers(): Promise<Array<Layer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLayers();
            return result;
        }
    }
    async listProductionEntries(): Promise<Array<ProductionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductionEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductionEntries();
            return result;
        }
    }
    async listRMs(): Promise<Array<RM>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRMs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRMs();
            return result;
        }
    }
    async updateGrade(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGrade(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGrade(arg0, arg1, arg2);
            return result;
        }
    }
    async updateGsmRange(arg0: bigint, arg1: string, arg2: number, arg3: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGsmRange(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGsmRange(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLayer(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLayer(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRM(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRM(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRM(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CostingRecord]): CostingRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Grade]): Grade | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GsmRange]): GsmRange | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Layer]): Layer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RM]): RM | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
